import Bookmaker from '#models/bookmaker'

export const DEFAULT_BOOKMAKERS: { name: string; website: string | null }[] = [
  { name: '10Game', website: null },
  { name: '1Pra1', website: 'https://www.1pra1.bet.br' },
  { name: '1xBet', website: 'https://1xbet.bet.br' },
  { name: '20Bet', website: 'https://20bet.com' },
  { name: '22Bet', website: 'https://22bet.com' },
  { name: '4Play', website: 'https://4play.bet.br' },
  { name: '4Win', website: 'https://4win.bet.br' },
  { name: '6R', website: 'https://6r.bet.br' },
  { name: '7Games', website: 'https://7games.bet.br' },
  { name: '9D', website: 'https://9d.bet.br' },
  { name: '9F', website: 'https://9f.bet.br' },
  { name: 'A247', website: 'https://a247.bet.br' },
  { name: 'Afun', website: 'https://afun.bet.br' },
  { name: 'Alfabet', website: 'https://alfa.bet.br' },
  { name: 'Aposta Ganha', website: 'https://apostaganha.bet.br' },
  { name: 'Aposta Online', website: 'https://apostaonline.bet.br' },
  { name: 'Aposta1', website: 'https://www.aposta1.bet.br' },
  { name: 'Apostabet', website: 'https://aposta.bet.br' },
  { name: 'Apostamax', website: 'https://apostamax.bet.br' },
  { name: 'Apostar', website: 'https://apostar.bet.br' },
  { name: 'Apostatudo', website: 'https://apostatudo.bet.br' },
  { name: 'Apostefacil', website: 'https://apostefacil.com.br' },
  { name: 'Apostou', website: 'https://www.apostou.bet.br' },
  { name: 'Aviao', website: 'https://www.aviao.bet.br' },
  { name: 'B1Bet', website: 'https://b1bet.bet.br' },
  { name: 'B2xBet', website: 'https://b2xbet.com.br' },
  { name: 'Bandbet', website: 'https://www.bandbet.bet.br' },
  { name: 'Bateubet', website: 'https://bateu.bet.br' },
  { name: 'BC.Game', website: 'https://bcgame.com' },
  { name: 'Bet da Sorte', website: 'https://www.betdasorte.bet.br' },
  { name: 'Bet.App', website: 'https://betapp.bet.br' },
  { name: 'Bet.Bet', website: 'https://betbet.com.br' },
  { name: 'Bet365', website: 'https://www.bet365.bet.br' },
  { name: 'Bet4', website: 'https://bet4.bet.br' },
  { name: 'Bet7K', website: 'https://7k.bet.br' },
  { name: 'Betagora', website: null },
  { name: 'Betano', website: 'https://www.betano.bet.br' },
  { name: 'Betboo', website: 'https://www.betboo.bet.br' },
  { name: 'Betboom', website: 'https://betboom.bet.br' },
  { name: 'Betbra Tradeball', website: 'https://betbra.bet.br' },
  { name: 'Betbuffalo', website: null },
  { name: 'Betespecial', website: 'https://betespecial.bet.br' },
  { name: 'Betesporte', website: 'https://betesporte.bet.br' },
  { name: 'Betfair', website: 'https://www.betfair.bet.br' },
  { name: 'Betfalcons', website: 'https://betfalcons.bet.br' },
  { name: 'Betfast', website: 'https://betfast.bet.br' },
  { name: 'Betfusion', website: 'https://betfusion.bet.br' },
  { name: 'Betgo', website: 'https://betgo.bet.br' },
  { name: 'Betgorillas', website: 'https://betgorillas.bet.br' },
  { name: 'Betmaster', website: 'https://betmaster.com.br' },
  { name: 'BetMGM', website: 'https://www.betmgm.bet.br' },
  { name: 'Betnacional', website: 'https://betnacional.bet.br' },
  { name: 'Betou Bet', website: 'https://betou.bet.br' },
  { name: 'Betpark', website: null },
  { name: 'Betpix365', website: 'https://www.betpix365.bet.br' },
  { name: 'Betsson', website: 'https://www.betsson.bet.br' },
  { name: 'Betsul', website: 'https://betsul.bet.br' },
  { name: 'BetVIP', website: 'https://betvip.bet.br' },
  { name: 'Betwarrior', website: 'https://betwarrior.bet.br' },
  { name: 'Betwinner', website: 'https://betwinner.com' },
  { name: 'Betão', website: 'https://betao.bet.br' },
  { name: 'Big Bet', website: 'https://big.bet.br' },
  { name: 'Blaze', website: 'https://blaze.bet.br' },
  { name: 'Bolsa Tradeball', website: 'https://bolsadeaposta.bet.br' },
  { name: 'BR4Bet', website: 'https://br4.bet.br' },
  { name: 'Brasil Bet', website: 'https://brasil.bet.br' },
  { name: 'Brasil Da Sorte', website: 'https://brasildasorte.bet.br' },
  { name: 'Brazino777', website: 'https://www.brazino777.bet.br' },
  { name: 'Brbet', website: 'https://www.brbet.bet.br' },
  { name: 'BRX', website: 'https://brx.bet.br' },
  { name: 'Bullsbet', website: 'https://bullsbet.bet.br' },
  { name: 'Casa De Apostas', website: 'https://casadeapostas.bet.br' },
  { name: 'Cassino Bet', website: 'https://cassino.bet.br' },
  { name: 'CBEsportes', website: 'https://cbesportes.bet.br' },
  { name: 'Claze', website: null },
  { name: 'Dafabet', website: 'https://dafabet.com' },
  { name: 'Donosdabola', website: 'https://donosdabola.bet.br' },
  { name: 'Energia', website: 'https://energia.bet.br' },
  { name: 'Esporte365', website: 'https://esporte365.com.br' },
  { name: 'Esportes da Sorte', website: 'https://esportesdasorte.bet.br' },
  { name: 'Esportiva', website: 'https://esportiva.bet.br' },
  { name: 'Esportivavip', website: 'https://esportivavip.bet.br' },
  { name: 'EstrelaBet', website: 'https://www.estrelabet.bet.br' },
  { name: 'F12.bet', website: 'https://f12.bet.br' },
  { name: 'Fanbit', website: 'https://fanbit.bet.br' },
  { name: 'Faz1bet', website: 'https://faz1.bet.br' },
  { name: 'Fazobet', website: 'https://fazo.bet.br' },
  { name: 'Fogo777', website: 'https://fogo777.bet.br' },
  { name: 'Fulltbet', website: 'https://fulltbet.bet.br' },
  { name: 'Galerabet', website: 'https://galera.bet.br' },
  { name: 'Ganheibet', website: 'https://ganhei.bet.br' },
  { name: 'Geralbet', website: 'https://geralbet.bet.br' },
  { name: 'Goldebet', website: 'https://goldebet.bet.br/' },
  { name: 'H2Bet', website: 'https://h2.bet.br' },
  { name: 'Hanzbet', website: 'https://hanz.bet.br' },
  { name: 'Hiperbet', website: 'https://hiper.bet.br' },
  { name: 'Icebet', website: 'https://ice.bet.br' },
  { name: 'Ijogo', website: 'https://ijogo.bet.br' },
  { name: 'Joga Junto', website: 'https://www.jogajunto.bet.br' },
  { name: 'Jogo de Ouro', website: 'https://jogodeouro.bet.br' },
  { name: 'Jogão', website: 'https://jogao.bet.br' },
  { name: 'Jonbet', website: 'https://jonbet.bet.br' },
  { name: 'Kingpanda', website: 'https://kingpanda.bet.br' },
  { name: 'KTO', website: 'https://www.kto.bet.br' },
  { name: 'Lancedesorte', website: 'https://lancedesorte.bet.br' },
  { name: 'Leon.Bet', website: null },
  { name: 'Leovegas', website: 'https://leovegas.com' },
  { name: 'Liderbet', website: 'https://lider.bet.br' },
  { name: 'Lotogreen', website: 'https://lotogreen.bet.br' },
  { name: 'Lottoland', website: 'https://www.lottoland.bet.br' },
  { name: 'Lottu', website: 'https://www.lottu.bet.br' },
  { name: 'Luckbet', website: 'https://luck.bet.br' },
  { name: 'Luvabet', website: 'https://luva.bet.br' },
  { name: 'Marjosports', website: 'https://www.marjosports.com.br' },
  { name: 'Matchbook', website: 'https://matchbook.bet.br' },
  { name: 'Maximabet', website: 'https://maxima.bet.br' },
  { name: 'McGames', website: 'https://mcgames.bet.br' },
  { name: 'Melbet', website: 'https://melbet.com' },
  { name: 'Meridianbet', website: 'https://meridianbet.bet.br' },
  { name: 'MMABet', website: 'https://mmabet.bet.br' },
  { name: 'Mr.Jack.Bet', website: null },
  { name: 'Multibet', website: 'https://multi.bet.br' },
  { name: 'Novibet', website: 'https://www.novibet.bet.br' },
  { name: 'Obabet', website: 'https://obabet.bet.br' },
  { name: 'Onabet', website: 'https://ona.bet.br' },
  { name: 'P9', website: 'https://p9.bet.br' },
  { name: 'Pagbet', website: null },
  { name: 'Pagol', website: 'https://pagol.bet.br' },
  { name: 'Papigames', website: 'https://papigames.bet.br' },
  { name: 'Parimatch', website: 'https://parimatch.com' },
  { name: 'Pinnacle', website: 'https://pinnacle.bet.br' },
  { name: 'Pixbet', website: 'https://pix.bet.br' },
  { name: 'Playbet', website: 'https://play.bet.br' },
  { name: 'Playpix', website: null },
  { name: 'R7', website: 'https://r7.bet.br' },
  { name: 'Receba Bet', website: 'https://receba.bet.br' },
  { name: 'Rei do Pitaco', website: 'https://pitaco.bet.br' },
  { name: 'Seguro Bet', website: 'https://www.seguro.bet.br' },
  { name: 'Seubet', website: 'https://seu.bet.br' },
  { name: 'Sorte na Bet', website: 'https://sortenabet.bet.br' },
  { name: 'Sorteonline', website: 'https://www.sorteonline.bet.br' },
  { name: 'Spinbet', website: 'https://spin.bet.br' },
  { name: 'Sportingbet', website: 'https://www.sportingbet.bet.br' },
  { name: 'Sportybet', website: 'https://sporty.bet.br' },
  { name: 'Stake', website: 'https://stake.bet.br' },
  { name: 'Start Bet', website: 'https://start.bet.br' },
  { name: 'Superbet', website: 'https://superbet.bet.br' },
  { name: 'Supremabet', website: 'https://suprema.bet.br' },
  { name: 'Tivobet', website: 'https://tivo.bet.br' },
  { name: 'Ultrabet', website: 'https://ultra.bet.br' },
  { name: 'Upbet', website: 'https://up.bet.br' },
  { name: 'UX Bet', website: 'https://uxbet.com.br' },
  { name: 'Vaidebet', website: 'https://www.vaidebet.bet.br' },
  { name: 'Vbet', website: 'https://www.vbet.bet.br' },
  { name: 'Vera', website: 'https://vera.bet.br' },
  { name: 'Versus', website: 'https://www.versus.bet.br' },
  { name: 'Vivasorte', website: 'https://vivasorte.bet.br' },
  { name: 'Vupi Bet', website: 'https://vupi.bet.br' },
  { name: 'WJCasino', website: 'https://wjcasino.bet.br' },
]

export async function seedDefaultBookmakers(userId: number) {
  await Bookmaker.createMany(DEFAULT_BOOKMAKERS.map((bookmaker) => ({ userId, ...bookmaker })))
}
