import Bookmaker from '#models/bookmaker'

export const DEFAULT_BOOKMAKERS: { name: string; website: string | null }[] = [
  { name: '4Play', website: 'https://4play.bet.br' },
  { name: '7Games', website: 'https://7games.bet.br' },
  { name: 'Apostabet', website: 'https://aposta.bet.br' },
  { name: 'Aposta Ganha', website: 'https://apostaganha.bet.br' },
  { name: 'Bandbet', website: 'https://www.bandbet.bet.br' },
  { name: 'Bet365', website: 'https://www.bet365.bet.br' },
  { name: 'Bet7K', website: 'https://7k.bet.br' },
  { name: 'Betano', website: 'https://www.betano.bet.br' },
  { name: 'Betão', website: 'https://betao.bet.br' },
  { name: 'Bet da Sorte', website: 'https://www.betdasorte.bet.br' },
  { name: 'Betesporte', website: 'https://betesporte.bet.br' },
  { name: 'Betfair', website: 'https://www.betfair.bet.br' },
  { name: 'Betfast', website: 'https://betfast.bet.br' },
  { name: 'Betfusion', website: 'https://betfusion.bet.br' },
  { name: 'BetMGM', website: 'https://www.betmgm.bet.br' },
  { name: 'Betnacional', website: 'https://betnacional.bet.br' },
  { name: 'Betpix365', website: 'https://www.betpix365.bet.br' },
  { name: 'Betsson', website: 'https://www.betsson.bet.br' },
  { name: 'BetVIP', website: 'https://betvip.bet.br' },
  { name: 'Betbra Tradeball', website: 'https://betbra.bet.br' },
  { name: 'Bolsa Tradeball', website: 'https://bolsadeaposta.bet.br' },
  { name: 'BR4Bet', website: 'https://br4.bet.br' },
  { name: 'Brbet', website: 'https://www.brbet.bet.br' },
  { name: 'Cassino Bet', website: 'https://cassino.bet.br' },
  { name: 'Esportes da Sorte', website: 'https://esportesdasorte.bet.br' },
  { name: 'Esportiva', website: 'https://esportiva.bet.br' },
  { name: 'EstrelaBet', website: 'https://www.estrelabet.bet.br' },
  { name: 'F12.bet', website: 'https://f12.bet.br' },
  { name: 'Ganheibet', website: 'https://ganhei.bet.br' },
  { name: 'Goldebet', website: 'https://goldebet.bet.br/' },
  { name: 'Hiperbet', website: 'https://hiper.bet.br' },
  { name: 'Jogo de Ouro', website: 'https://jogodeouro.bet.br' },
  { name: 'Kingpanda', website: 'https://kingpanda.bet.br' },
  { name: 'KTO', website: 'https://www.kto.bet.br' },
  { name: 'Lotogreen', website: 'https://lotogreen.bet.br' },
  { name: 'Marjosports', website: 'https://www.marjosports.com.br' },
  { name: 'McGames', website: 'https://mcgames.bet.br' },
  { name: 'Novibet', website: 'https://www.novibet.bet.br' },
  { name: 'Pagol', website: 'https://pagol.bet.br' },
  { name: 'Pixbet', website: 'https://pix.bet.br' },
  { name: 'R7', website: 'https://r7.bet.br' },
  { name: 'Rei do Pitaco', website: 'https://pitaco.bet.br' },
  { name: 'Seguro Bet', website: 'https://www.seguro.bet.br' },
  { name: 'Sorte na Bet', website: 'https://sortenabet.bet.br' },
  { name: 'Sportingbet', website: 'https://www.sportingbet.bet.br' },
  { name: 'Sportybet', website: 'https://sporty.bet.br' },
  { name: 'Stake', website: 'https://stake.bet.br' },
  { name: 'Superbet', website: 'https://superbet.bet.br' },
  { name: 'Vera', website: 'https://vera.bet.br' },
  { name: 'Vivasorte', website: 'https://vivasorte.bet.br' },
]

export async function seedDefaultBookmakers(userId: number) {
  await Bookmaker.createMany(DEFAULT_BOOKMAKERS.map((bookmaker) => ({ userId, ...bookmaker })))
}
